### ISSUE TITLE
+mq(retina) throws error

### ISSUE THREAD

**Issue by DotCoyote** [jonsuh/mq-sass#2]
Hi,

I'm using your mixin with gulp-sass and pure Sass-syntax.

When i try to use the retina-function `+mq(retina)` I get the following error:

`Error: [gulp-sass]
 Error: Function mq-get-breakpoint-width did not return a value
        on line 182 of sites/all/themes/dtag_cr_2016/bower/sass-mq/_mq.scss
            $min-width: mq-px2em(mq-get-breakpoint-width($from, $breakpoints))`

**Comment by jonsuh** [comment]
@CinKon This is the incorrect library. You would want to open the issue at https://github.com/sass-mq/sass-mq
